language: node_js
node_js:
  - 18
cache:
  directories:
    - node_modules
script:
  - npm run build || true
  - npm test
os: linux
dist: focal
strategy: git
deploy:
  provider: netlify
  site: elaborate-manatee-ca4881
  auth: $NETLIFY_TOKEN
  edge: true # opt in to dpl v2